// Export a note as a standalone .html file, and read one back.
//
// The file renders the note — Markdown and TeX — on its own in any browser: the
// libraries come from a CDN (pinned to the same versions this app vendors, so
// the output is identical), the original Markdown is embedded verbatim, and a
// small inline script renders it. There is no editor, menu or toolbar.
//
// The Markdown is HTML-escaped inside a `<script type="text/markdown">` block:
// escaping means the content can never contain `</script>` to break out, and it
// round-trips byte-for-byte, so dragging the file back in restores the source
// exactly rather than reverse-engineering it from rendered HTML.
//
// Two switches — see docs/HTML_EXPORT.md:
//   css: 'cdn'    github-markdown-css, or 'inline' — a self-contained stylesheet
//   js:  'min'    the pre-minified renderer, or 'full' — the readable copy
const OPTIONS = {
  css: 'cdn',
  js: 'min',
}

const CDN = 'https://cdn.jsdelivr.net/npm'
const MARKED_URL = `${CDN}/marked@18.0.9/lib/marked.umd.min.js`
const PURIFY_URL = `${CDN}/dompurify@3.4.13/dist/purify.min.js`
const KATEX_JS = `${CDN}/katex@0.18.2/dist/katex.min.js`
const KATEX_CSS = `${CDN}/katex@0.18.2/dist/katex.min.css`
// GitHub's own Markdown stylesheet (light + dark) for the `css: 'cdn'` option;
// it styles the `.markdown-body` container.
const GH_MD_CSS = `${CDN}/github-markdown-css@5/github-markdown.min.css`

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ))
}

function unescapeHtml(s) {
  return String(s ?? '')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
}

// The renderer that runs inside the exported file. It is written as a real
// function and serialised with `.toString()` so its regexes need no
// string-escaping and stay a faithful copy of src/viewer.js. It runs in the
// exported page against the CDN globals (marked, DOMPurify, katex); if those did
// not load — offline, or a blocked CDN — it falls back to showing the source as
// plain text. It must reference nothing from this module.
//
// The `js: 'min'` option ships RENDER_MIN below instead; regenerate that from
// this source with `python _tools/minify_render.py` after any edit here.
// >>> render-source >>>
function exportedRender() {
  var out = document.getElementById('content')
  var src = document.getElementById('md-source')
  var md = src
    ? src.textContent
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&amp;/g, '&')
    : ''

  if (typeof marked === 'undefined' || typeof DOMPurify === 'undefined') {
    out.textContent = md
    return
  }

  var KATEX_OPTS = { throwOnError: false, errorColor: '#b00020', strict: false }
  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
    })
  }
  function renderMath(tex, display) {
    try {
      return katex.renderToString(tex, Object.assign({}, KATEX_OPTS, { displayMode: display }))
    } catch (e) {
      return '<span class="katex-error">' + esc(e && e.message) + '</span>'
    }
  }

  marked.use({ gfm: true, breaks: false }, {
    extensions: [
      {
        name: 'mathBlock',
        level: 'block',
        start: function (s) { return s.indexOf('$$') },
        tokenizer: function (s) {
          var m = /^\$\$([\s\S]+?)\$\$(?:\n+|$)/.exec(s)
          if (m) return { type: 'mathBlock', raw: m[0], text: m[1].trim() }
        },
        renderer: function (t) { return renderMath(t.text, true) },
      },
      {
        name: 'mathInline',
        level: 'inline',
        start: function (s) { var i = s.indexOf('$'); return i < 0 ? undefined : i },
        tokenizer: function (s) {
          var m = /^\$(?![\s\d])([\s\S]*?[^\s\\])\$(?!\d)/.exec(s)
          if (m) return { type: 'mathInline', raw: m[0], text: m[1] }
        },
        renderer: function (t) { return renderMath(t.text, false) },
      },
    ],
  })

  DOMPurify.addHook('afterSanitizeAttributes', function (n) {
    if (n.tagName !== 'A') return
    var h = n.getAttribute('href') || ''
    if (!/^https?:/i.test(h)) return
    n.setAttribute('target', '_blank')
    n.setAttribute('rel', 'noopener noreferrer')
  })

  out.innerHTML = DOMPurify.sanitize(marked.parse(md), {
    USE_PROFILES: { html: true, mathMl: true, svg: true },
  })
}
// <<< render-source <<<

// Minified `(exportedRender)()`, generated by _tools/minify_render.py. Do not
// edit by hand; empty means "not generated yet", and the export falls back to
// the readable renderer.
// >>> render-min >>>
const RENDER_MIN = "(function exportedRender(){var out=document.getElementById('content')\nvar src=document.getElementById('md-source')\nvar md=src?src.textContent.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'\"').replace(/&#39;/g,\"'\").replace(/&amp;/g,'&'):''\nif(typeof marked==='undefined'||typeof DOMPurify==='undefined'){out.textContent=md\nreturn}\nvar KATEX_OPTS={throwOnError:false,errorColor:'#b00020',strict:false}\nfunction esc(s){return String(s).replace(/[&<>\"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]})}\nfunction renderMath(tex,display){try{return katex.renderToString(tex,Object.assign({},KATEX_OPTS,{displayMode:display}))}catch(e){return'<span class=\"katex-error\">'+esc(e&&e.message)+'</span>'}}\nmarked.use({gfm:true,breaks:false},{extensions:[{name:'mathBlock',level:'block',start:function(s){return s.indexOf('$$')},tokenizer:function(s){var m=/^\\$\\$([\\s\\S]+?)\\$\\$(?:\\n+|$)/.exec(s)\nif(m)return{type:'mathBlock',raw:m[0],text:m[1].trim()}},renderer:function(t){return renderMath(t.text,true)},},{name:'mathInline',level:'inline',start:function(s){var i=s.indexOf('$');return i<0?undefined:i},tokenizer:function(s){var m=/^\\$(?![\\s\\d])([\\s\\S]*?[^\\s\\\\])\\$(?!\\d)/.exec(s)\nif(m)return{type:'mathInline',raw:m[0],text:m[1]}},renderer:function(t){return renderMath(t.text,false)},},],})\nDOMPurify.addHook('afterSanitizeAttributes',function(n){if(n.tagName!=='A')return\nvar h=n.getAttribute('href')||''\nif(!/^https?:/i.test(h))return\nn.setAttribute('target','_blank')\nn.setAttribute('rel','noopener noreferrer')})\nout.innerHTML=DOMPurify.sanitize(marked.parse(md),{USE_PROFILES:{html:true,mathMl:true,svg:true},})})()"
// <<< render-min <<<

// github-markdown-css styles the container but not the page around it, so the
// only inline rule for the 'cdn' option is the page frame.
const WRAPPER_CSS = `
body { margin: 0; background: #fff; }
.markdown-body { box-sizing: border-box; max-width: 820px; margin: 0 auto; padding: 44px; }
.katex-error { color: #b00020; }
@media (max-width: 820px) { .markdown-body { padding: 24px 16px; } }
@media (prefers-color-scheme: dark) { body { background: #0d1117; } }
`

// The self-contained stylesheet for the 'inline' option — no third stylesheet
// from a CDN, at the cost of carrying its own light/dark theme.
const INLINE_CSS = `
:root { color-scheme: light dark; }
body { margin: 0; background: #fff; color: #1f2328; font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
#content { max-width: 44rem; margin: 0 auto; padding: 40px 24px 96px; }
#content h1, #content h2, #content h3, #content h4 { line-height: 1.25; margin: 1.4em 0 .5em; }
#content h1 { font-size: 1.9em; }
#content h2 { font-size: 1.5em; border-bottom: 1px solid #e1e4e8; padding-bottom: .2em; }
#content h3 { font-size: 1.2em; }
#content p, #content ul, #content ol, #content blockquote, #content table, #content pre { margin: 0 0 1em; }
#content a { color: #0969da; }
#content code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: .9em; background: #f3f4f6; padding: .15em .35em; border-radius: 4px; }
#content pre { background: #f6f8fa; padding: 14px 16px; border-radius: 8px; overflow: auto; }
#content pre code { background: none; padding: 0; }
#content blockquote { padding-left: 1em; border-left: 3px solid #d0d7de; color: #57606a; }
#content table { border-collapse: collapse; }
#content th, #content td { border: 1px solid #d0d7de; padding: 6px 12px; }
#content img { max-width: 100%; }
.katex-error { color: #b00020; }
@media (prefers-color-scheme: dark) {
  body { background: #0d1117; color: #e6edf3; }
  #content h2 { border-color: #30363d; }
  #content a { color: #4493f8; }
  #content code { background: #21262d; }
  #content pre { background: #161b22; }
  #content blockquote { border-color: #30363d; color: #9198a1; }
  #content th, #content td { border-color: #30363d; }
}
`

/** A self-contained HTML document that renders `markdown` on its own. */
export function buildStandaloneHtml(name, markdown) {
  const title = escapeHtml((name || '').replace(/\.md$/i, '') || 'note')
  const source = escapeHtml(markdown ?? '')
  const render = OPTIONS.js === 'min' && RENDER_MIN
    ? RENDER_MIN
    : `(${exportedRender.toString()})()`
  const head = OPTIONS.css === 'cdn'
    ? `<link rel="stylesheet" href="${GH_MD_CSS}">\n<style>${WRAPPER_CSS}</style>`
    : `<style>${INLINE_CSS}</style>`
  const cssClass = OPTIONS.css === 'cdn' ? ' class="markdown-body"' : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<script src="${MARKED_URL}"></script>
<script src="${PURIFY_URL}"></script>
<script src="${KATEX_JS}"></script>
<link rel="stylesheet" href="${KATEX_CSS}">
${head}
</head>
<body>
<article id="content"${cssClass}>Rendering…</article>
<script type="text/markdown" id="md-source">${source}</script>
<script>${render}</script>
</body>
</html>
`
}

/**
 * If `html` is a file this app exported, pull the note's Markdown back out of
 * it. Any other HTML returns null, so the caller can fall back to treating it as
 * plain text. The note's name is the caller's job — it comes from the filename.
 */
export function extractMarkdown(html) {
  try {
    const dom = new DOMParser().parseFromString(html, 'text/html')
    const el = dom.getElementById('md-source')
    return el ? unescapeHtml(el.textContent || '') : null
  } catch {
    return null
  }
}
